"""Postgres access layer (psycopg 3 + pgvector).

Every query that reads chunks/pages MUST filter by ``client_id`` (TRD §3): no
cross-client results, ever. Write helpers here do NOT commit — the caller owns
the transaction (see :func:`linker.ingest.ingest_file`), so a whole ingest is
atomic. :func:`ensure_schema` is the exception: DDL is committed on apply.
"""
from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import psycopg
from pgvector.psycopg import register_vector

# schema.sql lives at the repository root, one level above this package.
SCHEMA_PATH = Path(__file__).resolve().parent.parent / "schema.sql"

ChunkRow = tuple[int, str, np.ndarray]  # (chunk_index, content, embedding)


@dataclass(frozen=True)
class ExactTarget:
    """A candidate target page from the exact-keyword pass (TRD §6 Step A).

    Carries the raw signal material the matcher blends into a heuristic relevance
    score (see :func:`linker.matcher.rank_candidates`). ``matched_content`` is the
    page's keyword-bearing chunks joined in document order — used to locate the
    first occurrence and to look for the keyword in a heading. The defaults on the
    signal fields keep older call sites and tests that only set the ranking-neutral
    fields working.
    """

    page_id: int
    url: str
    title: str | None
    hits: int  # number of the page's chunks whose content contains the keyword
    in_title: bool  # whether the keyword appears in the page title
    first_chunk_index: int = 0  # index of the earliest chunk that contains the keyword
    matched_content: str = ""  # the keyword-bearing chunks, joined in document order


def connect(database_url: str, *, apply_schema: bool = True) -> psycopg.Connection:
    """Open a Postgres connection with pgvector registered.

    When ``apply_schema`` is True (the default, used by ingestion) the schema is
    applied first so the ``vector`` extension exists before the type is
    registered. Read paths that assume an already-provisioned database (e.g. the
    ``suggest`` matcher) pass ``apply_schema=False`` to skip the DDL round-trip.
    """
    conn = psycopg.connect(database_url)
    if apply_schema:
        ensure_schema(conn)
    register_vector(conn)
    return conn


def ensure_schema(conn: psycopg.Connection, schema_path: Path | None = None) -> None:
    """Apply ``schema.sql`` idempotently (extension, tables, indexes) and commit."""
    sql = (schema_path or SCHEMA_PATH).read_text(encoding="utf-8")
    with conn.cursor() as cur:
        cur.execute(sql)
    conn.commit()


def upsert_client(conn: psycopg.Connection, name: str) -> int:
    """Insert the client if new (idempotent); return its id."""
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO clients (name) VALUES (%s)
            ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
            RETURNING id
            """,
            (name,),
        )
        return cur.fetchone()[0]


def upsert_page(
    conn: psycopg.Connection,
    client_id: int,
    url: str,
    title: str | None,
    char_count: int,
) -> int:
    """Insert/update a page keyed by (client_id, url); return its id."""
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO pages (client_id, url, title, char_count)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (client_id, url) DO UPDATE
              SET title = EXCLUDED.title,
                  char_count = EXCLUDED.char_count,
                  ingested_at = now()
            RETURNING id
            """,
            (client_id, url, title, char_count),
        )
        return cur.fetchone()[0]


def delete_page_chunks(conn: psycopg.Connection, page_id: int) -> None:
    """Delete all chunks for a page so re-ingest is idempotent (delete-then-insert)."""
    with conn.cursor() as cur:
        cur.execute("DELETE FROM chunks WHERE page_id = %s", (page_id,))


def insert_chunks(
    conn: psycopg.Connection,
    client_id: int,
    page_id: int,
    rows: Iterable[ChunkRow],
) -> int:
    """Insert chunk rows for a page; return the number inserted.

    ``rows`` yields ``(chunk_index, content, embedding)`` where ``embedding`` is a
    768-d float32 ndarray (adapted to pgvector). ``tsv`` is generated by Postgres.
    """
    rows = list(rows)
    if not rows:
        return 0
    with conn.cursor() as cur:
        cur.executemany(
            """
            INSERT INTO chunks (client_id, page_id, chunk_index, content, embedding)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (page_id, chunk_index) DO UPDATE
              SET content = EXCLUDED.content,
                  embedding = EXCLUDED.embedding
            """,
            [(client_id, page_id, ci, content, emb) for ci, content, emb in rows],
        )
    return len(rows)


def get_client_id(conn: psycopg.Connection, name: str) -> int | None:
    """Return the id of the client named ``name``, or None if it does not exist.

    Read-only counterpart to :func:`upsert_client` (which would create the row).
    Used by the matcher to resolve a client name to the ``client_id`` that every
    downstream query filters on.
    """
    with conn.cursor() as cur:
        cur.execute("SELECT id FROM clients WHERE name = %s", (name,))
        row = cur.fetchone()
    return row[0] if row else None


def find_exact_target_candidates(
    conn: psycopg.Connection,
    client_id: int,
    keyword: str,
    current_url: str | None,
    limit: int,
) -> list[ExactTarget]:
    """Return the candidate target pages for the exact-keyword pass (TRD §6 A).

    This is the TRD §6 Step A base query — pages of ``client_id`` whose chunk
    content contains ``keyword`` (case-insensitive substring), excluding the
    current post's own URL (``p.url IS DISTINCT FROM :current_url``; a NULL
    ``current_url`` excludes nothing) — widened to return a candidate *pool*
    (capped at ``limit``) rather than a single winner, so the matcher can re-rank
    it by relevance signals. Every filter is scoped by ``client_id`` — no
    cross-client results.

    Alongside the original ``hits``/``in_title`` signals it returns, per page:
      * ``first_chunk_index`` — the lowest chunk index that contains the keyword
        (a coarse "how early in the post" proxy), and
      * ``matched_content`` — that page's keyword-bearing chunks joined in
        document order, so the matcher can pinpoint the first occurrence and scan
        for the keyword in a heading without a second round-trip.

    The pool is ordered by the original ``in_title DESC, hits DESC`` so that when
    it is smaller than the number of matching pages, the strongest-by-the-old-
    heuristic pages are the ones kept for re-ranking.
    """
    kw_like = f"%{keyword}%"
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT p.id, p.url, p.title, count(*) AS hits,
                   bool_or(p.title ILIKE %(kw_like)s) AS in_title,
                   min(c.chunk_index) AS first_chunk_index,
                   string_agg(c.content, E'\\n' ORDER BY c.chunk_index) AS matched_content
            FROM chunks c JOIN pages p ON p.id = c.page_id
            WHERE c.client_id = %(cid)s
              AND p.url IS DISTINCT FROM %(current_url)s
              AND c.content ILIKE %(kw_like)s
            GROUP BY p.id, p.url, p.title
            ORDER BY in_title DESC, hits DESC
            LIMIT %(limit)s
            """,
            {
                "kw_like": kw_like,
                "cid": client_id,
                "current_url": current_url,
                "limit": limit,
            },
        )
        rows = cur.fetchall()
    return [
        ExactTarget(
            page_id=row[0],
            url=row[1],
            title=row[2],
            hits=row[3],
            in_title=bool(row[4]),
            first_chunk_index=row[5] or 0,
            matched_content=row[6] or "",
        )
        for row in rows
    ]


def embedding_column_dim(conn: psycopg.Connection) -> int | None:
    """Return the declared dimension of ``chunks.embedding`` (e.g. 768), or None.

    Reads the column's type modifier (``vector(768)`` -> 768) so ingestion can
    fail fast when ``EMBED_DIM`` disagrees with the schema, before any embeddings
    are computed. Returns None if the dimension cannot be determined.
    """
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT format_type(a.atttypid, a.atttypmod)
            FROM pg_attribute a
            WHERE a.attrelid = 'chunks'::regclass
              AND a.attname = 'embedding'
              AND NOT a.attisdropped
            """
        )
        row = cur.fetchone()
    if not row or not row[0]:
        return None
    type_text = row[0]  # e.g. "vector(768)"
    open_paren, close_paren = type_text.find("("), type_text.find(")")
    if open_paren == -1 or close_paren <= open_paren:
        return None
    try:
        return int(type_text[open_paren + 1 : close_paren])
    except ValueError:
        return None


def ingest_stats(conn: psycopg.Connection, client_id: int) -> dict[str, int]:
    """Return verification counts for a client (TRD §11 M1 acceptance check)."""
    with conn.cursor() as cur:
        cur.execute("SELECT count(*) FROM pages WHERE client_id = %s", (client_id,))
        pages = cur.fetchone()[0]
        cur.execute("SELECT count(*) FROM chunks WHERE client_id = %s", (client_id,))
        chunks = cur.fetchone()[0]
        cur.execute(
            "SELECT count(*) FROM chunks WHERE client_id = %s AND embedding IS NULL",
            (client_id,),
        )
        null_embeddings = cur.fetchone()[0]
        cur.execute(
            """
            SELECT count(*) FROM pages p
            WHERE p.client_id = %s
              AND NOT EXISTS (SELECT 1 FROM chunks c WHERE c.page_id = p.id)
            """,
            (client_id,),
        )
        pages_without_chunks = cur.fetchone()[0]
    return {
        "pages": pages,
        "chunks": chunks,
        "null_embeddings": null_embeddings,
        "pages_without_chunks": pages_without_chunks,
    }
